vich_uploader:
    db_driver: orm

    metadata:
        type: attribute

    mappings:
        blog:
            uri_prefix: assets/images/blog
            upload_destination: '%kernel.project_dir%/public/assets/images/blog'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true